[client]

# https://docs.streamlit.io/library/advanced-features/configuration#client
# Controls whether the default sidebar page navigation in a multipage app is
# displayed.
# Default: true
showSidebarNavigation = false
